-- Capture user and workload schema for the lab database.
-- From plan increment P0-12 this file is the committed output of
--   oracle-cdc-doctor setup-sql --profile lab
-- and a CI test asserts they match. Grants follow docs/research/logminer_reference.md section 2.
WHENEVER SQLERROR EXIT FAILURE

-- Common user: mines at CDB$ROOT and reads every PDB (PRD-00 CORE-MINE-9).
CREATE USER c##cdc IDENTIFIED BY "cdc" CONTAINER=ALL;
ALTER USER c##cdc QUOTA UNLIMITED ON users CONTAINER=ALL;
-- A common user sees container data objects (V$PDBS, V$SESSION, V$LOGMNR_CONTENTS, CDB_ views)
-- only for containers in its CONTAINER_DATA set, which defaults to CDB$ROOT alone. Mining at root
-- for several PDBs needs all of them (doctor rule DOC-4 checks this).
ALTER USER c##cdc SET CONTAINER_DATA=ALL CONTAINER=CURRENT;

GRANT CREATE SESSION TO c##cdc CONTAINER=ALL;
GRANT SET CONTAINER TO c##cdc CONTAINER=ALL;
GRANT LOGMINING TO c##cdc CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO c##cdc CONTAINER=ALL;
GRANT SELECT ANY TABLE TO c##cdc CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO c##cdc CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO c##cdc CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO c##cdc CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR TO c##cdc CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$THREAD TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO c##cdc CONTAINER=ALL;
GRANT SELECT ON GV_$TRANSACTION TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$SESSION TO c##cdc CONTAINER=ALL;
GRANT SELECT ON GV_$SESSION TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$PROCESS TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$PDBS TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$VERSION TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$PARAMETER TO c##cdc CONTAINER=ALL;
GRANT SELECT ON V_$SQL TO c##cdc CONTAINER=ALL;

-- Lab only: lets tests force log switches and kill sessions through the capture connection.
GRANT ALTER SYSTEM TO c##cdc CONTAINER=ALL;
GRANT ALTER SESSION TO c##cdc CONTAINER=ALL;

-- Workload schema in every PDB: the bench generator runs here; its ledger is excluded from capture.
ALTER SESSION SET CONTAINER = FREEPDB1;
CREATE USER workload IDENTIFIED BY "workload" QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO workload;
GRANT SELECT ON V_$DATABASE TO workload;

ALTER SESSION SET CONTAINER = FREEPDB2;
CREATE USER workload IDENTIFIED BY "workload" QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO workload;
GRANT SELECT ON V_$DATABASE TO workload;

ALTER SESSION SET CONTAINER = FREEPDB3;
CREATE USER workload IDENTIFIED BY "workload" QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO workload;
GRANT SELECT ON V_$DATABASE TO workload;

ALTER SESSION SET CONTAINER = CDB$ROOT;
