/*
 * Copyright 2026 OSO DevOps Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package sh.oso.connect.oracle.core.doctor;

import java.time.Duration;
import java.util.List;
import java.util.Locale;
import sh.oso.connect.oracle.core.topology.Platform;

/**
 * Generates the DBA script for the capture user (PRD-05 setup-sql). The lab profile is the exact
 * content of docker/test-oracle/initdb.d/04-capture-user.sql, which a CI test asserts.
 */
public final class SetupSql {

  public enum Profile {
    PRODUCTION,
    LAB
  }

  static final List<String> V_VIEWS =
      List.of(
          "V_$DATABASE",
          "V_$LOG",
          "V_$LOGFILE",
          "V_$ARCHIVED_LOG",
          "V_$ARCHIVE_DEST_STATUS",
          "V_$THREAD",
          "V_$TRANSACTION",
          "GV_$TRANSACTION",
          "V_$SESSION",
          "GV_$SESSION",
          "V_$PROCESS",
          "V_$LOGMNR_CONTENTS",
          "V_$LOGMNR_LOGS",
          "V_$LOGMNR_PARAMETERS",
          "V_$PDBS",
          "V_$VERSION",
          "V_$PARAMETER",
          "V_$SQL");

  /** On RDS the master user grants these too: the engine reads them on every start. */
  static final List<String> RDS_EXTRA_VIEWS = List.of("V_$INSTANCE", "V_$CONTAINERS");

  /**
   * Archived redo hours the RDS script keeps: the DOC-10 need with the default journal threshold
   * and the default planned downtime, so DOC-23 stays quiet on a database set up by the script.
   */
  public static final long RDS_RETENTION_HOURS =
      Sizing.roundUpHours(DoctorContext.DEFAULT_MAX_DOWNTIME.plus(Duration.ofMinutes(5))).toHours();

  private SetupSql() {}

  public static String generate(
      String user,
      String password,
      boolean cdb,
      Profile profile,
      Platform platform,
      List<String> pdbs) {
    if (platform == Platform.RDS) {
      return rds(user, password);
    }
    if (platform != Platform.ONPREM) {
      return "-- " + platform.name().toLowerCase(Locale.ROOT) + " setup is not available yet.\n";
    }
    String all = cdb ? " CONTAINER=ALL" : "";
    StringBuilder sb = new StringBuilder();
    if (profile == Profile.LAB) {
      sb.append("-- Capture user and workload schema for the lab database.\n")
          .append("-- From plan increment P0-12 this file is the committed output of\n")
          .append("--   oracle-cdc-doctor setup-sql --profile lab\n")
          .append(
              "-- and a CI test asserts they match. Grants follow"
                  + " docs/research/logminer_reference.md section 2.\n");
    } else {
      sb.append("-- Capture user for the OSO CDC Connector for Oracle Database.\n")
          .append(
              "-- Generated by oracle-cdc-doctor setup-sql --profile production. Review before"
                  + " running as SYSDBA.\n");
    }
    sb.append("WHENEVER SQLERROR EXIT FAILURE\n\n");
    sb.append(
        cdb ? "-- Common user: mines at CDB$ROOT and reads every PDB.\n" : "-- Mining user.\n");
    sb.append("CREATE USER ")
        .append(user)
        .append(" IDENTIFIED BY \"")
        .append(password)
        .append('"')
        .append(all)
        .append(";\n");
    sb.append("ALTER USER ")
        .append(user)
        .append(" QUOTA UNLIMITED ON users")
        .append(all)
        .append(";\n");
    if (cdb) {
      sb.append(
              "-- A common user sees container data objects (V$PDBS, V$SESSION, V$LOGMNR_CONTENTS,"
                  + " CDB_ views)\n")
          .append(
              "-- only for containers in its CONTAINER_DATA set, which defaults to CDB$ROOT alone."
                  + " Mining at root\n")
          .append("-- for several PDBs needs all of them (doctor rule DOC-4 checks this).\n")
          .append("ALTER USER ")
          .append(user)
          .append(" SET CONTAINER_DATA=ALL CONTAINER=CURRENT;\n");
    }
    sb.append('\n');
    for (String p :
        List.of(
            "CREATE SESSION",
            "SET CONTAINER",
            "LOGMINING",
            "EXECUTE_CATALOG_ROLE",
            "SELECT ANY TABLE",
            "FLASHBACK ANY TABLE",
            "SELECT ANY DICTIONARY",
            "SELECT ANY TRANSACTION")) {
      if (!cdb && "SET CONTAINER".equals(p)) {
        continue;
      }
      sb.append("GRANT ").append(p).append(" TO ").append(user).append(all).append(";\n");
    }
    sb.append("GRANT EXECUTE ON DBMS_LOGMNR TO ").append(user).append(all).append(";\n");
    sb.append("GRANT EXECUTE ON DBMS_LOGMNR_D TO ").append(user).append(all).append(";\n");
    for (String v : V_VIEWS) {
      sb.append("GRANT SELECT ON ").append(v).append(" TO ").append(user).append(all).append(";\n");
    }
    if (profile == Profile.LAB) {
      sb.append(
          "\n"
              + "-- Lab only: lets tests force log switches and kill sessions through the capture"
              + " connection.\n");
      sb.append("GRANT ALTER SYSTEM TO ").append(user).append(all).append(";\n");
      sb.append("GRANT ALTER SESSION TO ").append(user).append(all).append(";\n");
      sb.append(
          "\n"
              + "-- Workload schema in every PDB: the bench generator runs here; its ledger is"
              + " excluded from capture.\n");
      for (String pdb : pdbs) {
        sb.append("ALTER SESSION SET CONTAINER = ").append(pdb).append(";\n");
        sb.append("CREATE USER workload IDENTIFIED BY \"workload\" QUOTA UNLIMITED ON users;\n");
        sb.append(
            "GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO"
                + " workload;\n");
        sb.append("GRANT SELECT ON V_$DATABASE TO workload;\n\n");
      }
      sb.append("ALTER SESSION SET CONTAINER = CDB$ROOT;\n");
    } else {
      sb.append("\n-- Per captured table (repeat for each): full before images for updates.\n");
      sb.append("-- ALTER TABLE <owner>.<table> ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;\n");
      sb.append("\n-- Database level, once:\n");
      sb.append("-- ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;\n");
    }
    return sb.toString();
  }

  /**
   * ADR-0024: the script for an RDS for Oracle non-CDB, run by the master user. RDS gives no
   * SYSDBA, ALTER SYSTEM or ALTER DATABASE: SYS objects are granted through grant_sys_object and
   * database settings change through rdsadmin procedures. A CDB instance, where the client always
   * connects to the tenant database as a local user, needs per-PDB mining, which this release does
   * not have.
   */
  static String rds(String user, String password) {
    String grantee = user.startsWith("\"") ? user.replace("\"", "") : user.toUpperCase(Locale.ROOT);
    StringBuilder sb = new StringBuilder();
    sb.append("-- Capture user for the OSO CDC Connector for Oracle Database on Amazon RDS for")
        .append(" Oracle (non-CDB).\n")
        .append(
            "-- Generated by oracle-cdc-doctor setup-sql --platform rds. Review, then run as the")
        .append(" RDS master user.\n")
        .append("-- RDS gives no SYSDBA, ALTER SYSTEM or ALTER DATABASE: SYS objects are granted")
        .append(" with\n")
        .append("-- rdsadmin.rdsadmin_util.grant_sys_object and database settings change through")
        .append(" rdsadmin procedures.\n")
        .append("-- An instance with the CDB architecture (21c and later, or a 19c CDB) needs")
        .append(" per-PDB mining, which this\n")
        .append("-- release does not have.\n")
        .append("WHENEVER SQLERROR EXIT FAILURE\n\n");
    sb.append("CREATE USER ")
        .append(user)
        .append(" IDENTIFIED BY \"")
        .append(password)
        .append("\";\n");
    sb.append("ALTER USER ").append(user).append(" QUOTA UNLIMITED ON users;\n\n");
    for (String p :
        List.of(
            "CREATE SESSION",
            "LOGMINING",
            "EXECUTE_CATALOG_ROLE",
            "SELECT ANY TABLE",
            "FLASHBACK ANY TABLE",
            "SELECT ANY DICTIONARY",
            "SELECT ANY TRANSACTION")) {
      sb.append("GRANT ").append(p).append(" TO ").append(user).append(";\n");
    }
    sb.append("\n-- SYS objects: names as in DBA_OBJECTS, grantee in upper case.\nBEGIN\n");
    for (String pkg : List.of("DBMS_LOGMNR", "DBMS_LOGMNR_D")) {
      sb.append(grantSysObject(pkg, grantee, "EXECUTE"));
    }
    for (List<String> views : List.of(V_VIEWS, RDS_EXTRA_VIEWS)) {
      for (String v : views) {
        sb.append(grantSysObject(v, grantee, "SELECT"));
      }
    }
    sb.append("END;\n/\n\n");
    sb.append("-- Minimal supplemental logging at database level.\n")
        .append("BEGIN\n")
        .append("  rdsadmin.rdsadmin_util.alter_supplemental_logging(p_action => 'ADD');\n")
        .append("END;\n/\n\n");
    sb.append("-- RDS deletes archived redo after this many hours (0 by default, which leaves a")
        .append(" stopped connector\n")
        .append("-- nothing to resume from). ")
        .append(RDS_RETENTION_HOURS)
        .append(" hours covers a day of downtime plus the journal threshold;\n")
        .append("-- size the allocated storage for that much redo (doctor rules DOC-10 and")
        .append(" DOC-23).\n")
        .append("BEGIN\n")
        .append("  rdsadmin.rdsadmin_util.set_configuration(\n")
        .append("    name  => 'archivelog retention hours',\n")
        .append("    value => '")
        .append(RDS_RETENTION_HOURS)
        .append("');\n")
        .append("END;\n/\nCOMMIT;\n\n");
    sb.append("-- RDS runs in ARCHIVELOG mode only while automated backups are on (backup")
        .append(" retention of 1 day or more).\n\n");
    sb.append("-- Per captured table (repeat for each), as the owner or the master user: full")
        .append(" before images for updates.\n")
        .append("-- ALTER TABLE <owner>.<table> ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;\n");
    return sb.toString();
  }

  private static String grantSysObject(String object, String grantee, String privilege) {
    return "  rdsadmin.rdsadmin_util.grant_sys_object('"
        + object
        + "', '"
        + grantee
        + "', '"
        + privilege
        + "');\n";
  }
}
