/*
 * Copyright 2026 OSO DevOps Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package sh.oso.connect.oracle.core.doctor;

import java.util.List;

/**
 * Generates the DBA script for the capture user (PRD-05 setup-sql). The lab profile is the exact
 * content of docker/test-oracle/initdb.d/04-capture-user.sql, which a CI test asserts.
 */
public final class SetupSql {

  public enum Profile {
    PRODUCTION,
    LAB
  }

  public enum Platform {
    ONPREM,
    RDS,
    AUTONOMOUS
  }

  static final List<String> V_VIEWS =
      List.of(
          "V_$DATABASE",
          "V_$LOG",
          "V_$LOGFILE",
          "V_$ARCHIVED_LOG",
          "V_$ARCHIVE_DEST_STATUS",
          "V_$THREAD",
          "V_$TRANSACTION",
          "GV_$TRANSACTION",
          "V_$SESSION",
          "GV_$SESSION",
          "V_$PROCESS",
          "V_$LOGMNR_CONTENTS",
          "V_$LOGMNR_LOGS",
          "V_$LOGMNR_PARAMETERS",
          "V_$PDBS",
          "V_$VERSION",
          "V_$PARAMETER",
          "V_$SQL");

  private SetupSql() {}

  public static String generate(
      String user,
      String password,
      boolean cdb,
      Profile profile,
      Platform platform,
      List<String> pdbs) {
    if (platform != Platform.ONPREM) {
      return "-- "
          + platform.name().toLowerCase()
          + " setup is not available yet (Phase "
          + (platform == Platform.RDS ? "2" : "3")
          + ").\n";
    }
    String all = cdb ? " CONTAINER=ALL" : "";
    StringBuilder sb = new StringBuilder();
    if (profile == Profile.LAB) {
      sb.append("-- Capture user and workload schema for the lab database.\n")
          .append("-- From plan increment P0-12 this file is the committed output of\n")
          .append("--   oracle-cdc-doctor setup-sql --profile lab\n")
          .append(
              "-- and a CI test asserts they match. Grants follow"
                  + " docs/research/logminer_reference.md section 2.\n");
    } else {
      sb.append("-- Capture user for the OSO CDC Connector for Oracle Database.\n")
          .append(
              "-- Generated by oracle-cdc-doctor setup-sql --profile production. Review before"
                  + " running as SYSDBA.\n");
    }
    sb.append("WHENEVER SQLERROR EXIT FAILURE\n\n");
    sb.append(
        cdb
            ? "-- Common user: mines at CDB$ROOT and reads every PDB (PRD-00 CORE-MINE-9).\n"
            : "-- Mining user.\n");
    sb.append("CREATE USER ")
        .append(user)
        .append(" IDENTIFIED BY \"")
        .append(password)
        .append('"')
        .append(all)
        .append(";\n");
    sb.append("ALTER USER ")
        .append(user)
        .append(" QUOTA UNLIMITED ON users")
        .append(all)
        .append(";\n");
    if (cdb) {
      sb.append(
              "-- A common user sees container data objects (V$PDBS, V$SESSION, V$LOGMNR_CONTENTS,"
                  + " CDB_ views)\n")
          .append(
              "-- only for containers in its CONTAINER_DATA set, which defaults to CDB$ROOT alone."
                  + " Mining at root\n")
          .append("-- for several PDBs needs all of them (doctor rule DOC-4 checks this).\n")
          .append("ALTER USER ")
          .append(user)
          .append(" SET CONTAINER_DATA=ALL CONTAINER=CURRENT;\n");
    }
    sb.append('\n');
    for (String p :
        List.of(
            "CREATE SESSION",
            "SET CONTAINER",
            "LOGMINING",
            "EXECUTE_CATALOG_ROLE",
            "SELECT ANY TABLE",
            "FLASHBACK ANY TABLE",
            "SELECT ANY DICTIONARY",
            "SELECT ANY TRANSACTION")) {
      if (!cdb && "SET CONTAINER".equals(p)) {
        continue;
      }
      sb.append("GRANT ").append(p).append(" TO ").append(user).append(all).append(";\n");
    }
    sb.append("GRANT EXECUTE ON DBMS_LOGMNR TO ").append(user).append(all).append(";\n");
    sb.append("GRANT EXECUTE ON DBMS_LOGMNR_D TO ").append(user).append(all).append(";\n");
    for (String v : V_VIEWS) {
      sb.append("GRANT SELECT ON ").append(v).append(" TO ").append(user).append(all).append(";\n");
    }
    if (profile == Profile.LAB) {
      sb.append(
          "\n"
              + "-- Lab only: lets tests force log switches and kill sessions through the capture"
              + " connection.\n");
      sb.append("GRANT ALTER SYSTEM TO ").append(user).append(all).append(";\n");
      sb.append("GRANT ALTER SESSION TO ").append(user).append(all).append(";\n");
      sb.append(
          "\n"
              + "-- Workload schema in every PDB: the bench generator runs here; its ledger is"
              + " excluded from capture.\n");
      for (String pdb : pdbs) {
        sb.append("ALTER SESSION SET CONTAINER = ").append(pdb).append(";\n");
        sb.append("CREATE USER workload IDENTIFIED BY \"workload\" QUOTA UNLIMITED ON users;\n");
        sb.append(
            "GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO"
                + " workload;\n");
        sb.append("GRANT SELECT ON V_$DATABASE TO workload;\n\n");
      }
      sb.append("ALTER SESSION SET CONTAINER = CDB$ROOT;\n");
    } else {
      sb.append("\n-- Per captured table (repeat for each): full before images for updates.\n");
      sb.append("-- ALTER TABLE <owner>.<table> ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;\n");
      sb.append("\n-- Database level, once:\n");
      sb.append("-- ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;\n");
    }
    return sb.toString();
  }
}
