/*
 * Copyright 2026 OSO DevOps Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package sh.oso.connect.oracle.e2e.support;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Deterministic markdown produced by the CORE-REF spikes and compared with the copy committed under
 * {@code oracle-cdc-core/src/main/resources/reference/}. Facts and decisions only, never timings
 * (Oracle's development licence forbids publishing benchmark results). Run with {@code
 * -Dreference.update=true} to rewrite the committed file; otherwise a difference fails the test and
 * the generated copy is left under {@code e2e-tests/target/reference/} for inspection.
 */
public final class ReferenceDoc {

  private final String name;
  private final StringBuilder body = new StringBuilder();

  public ReferenceDoc(String name, String title, String purpose) {
    this.name = name;
    body.append("# ").append(title).append("\n\n");
    body.append(purpose).append("\n\n");
    body.append("Generated by the `")
        .append(name)
        .append(
            "` spike in `e2e-tests` against Oracle Database Free and checked on every CI run. Edit"
                + " by re-running with `-Dreference.update=true`, never by hand.\n\n");
  }

  public ReferenceDoc section(String heading) {
    body.append("## ").append(heading).append("\n\n");
    return this;
  }

  public ReferenceDoc paragraph(String text) {
    body.append(text).append("\n\n");
    return this;
  }

  /**
   * Writes a table; rows are sorted by their first cell so output order never depends on Oracle.
   */
  public ReferenceDoc table(List<String> headers, List<List<String>> rows) {
    body.append("| ").append(String.join(" | ", headers)).append(" |\n");
    body.append("|")
        .append(headers.stream().map(h -> "---").collect(Collectors.joining("|")))
        .append("|\n");
    List<List<String>> sorted = new ArrayList<>(rows);
    sorted.sort((a, b) -> String.join("\u0000", a).compareTo(String.join("\u0000", b)));
    for (List<String> r : sorted) {
      body.append("| ")
          .append(r.stream().map(ReferenceDoc::cell).collect(Collectors.joining(" | ")))
          .append(" |\n");
    }
    body.append('\n');
    return this;
  }

  public ReferenceDoc bullet(String text) {
    body.append("- ").append(text).append('\n');
    return this;
  }

  public ReferenceDoc blank() {
    body.append('\n');
    return this;
  }

  public String render() {
    return body.toString();
  }

  /** Compares with the committed copy, or rewrites it when {@code -Dreference.update=true}. */
  public void assertUpToDate() throws IOException {
    Path repoRoot = Path.of(System.getProperty("repo.root", "..")).toAbsolutePath().normalize();
    Path committed =
        repoRoot.resolve("oracle-cdc-core/src/main/resources/reference/" + name + ".md");
    Path generated = repoRoot.resolve("e2e-tests/target/reference/" + name + ".md");
    Files.createDirectories(generated.getParent());
    String content = render();
    Files.writeString(generated, content, StandardCharsets.UTF_8);
    if (Boolean.getBoolean("reference.update")) {
      Files.createDirectories(committed.getParent());
      Files.writeString(committed, content, StandardCharsets.UTF_8);
      return;
    }
    assertThat(committed)
        .as("committed reference %s (run with -Dreference.update=true to create it)", committed)
        .exists();
    String expected = Files.readString(committed, StandardCharsets.UTF_8);
    assertThat(content)
        .as("reference %s differs from the committed copy; generated copy at %s", name, generated)
        .isEqualTo(expected);
  }

  private static String cell(String s) {
    return s == null ? "(null)" : s.replace("|", "\\|").replace("\n", " ");
  }
}
