// @ts-check
import {execSync} from 'node:child_process';

function getConnectorVersion() {
  if (process.env.CONNECTOR_VERSION) {
    return process.env.CONNECTOR_VERSION;
  }
  try {
    const json = execSync(
      'curl -sf https://api.github.com/repos/osodevops/kafka-connect-oracle-cdc/releases/latest',
      {encoding: 'utf8', timeout: 10000, stdio: ['pipe', 'pipe', 'pipe']}
    );
    return JSON.parse(json).tag_name;
  } catch {
    return 'unreleased';
  }
}

const connectorVersion = getConnectorVersion();

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      link: {type: 'doc', id: 'getting-started/index'},
      items: [
        'getting-started/quick-start',
        'getting-started/strimzi',
        'getting-started/installation',
        'getting-started/first-connector',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/how-capture-works',
        'concepts/transaction-buffer-and-journal',
        'concepts/offsets-and-recovery',
        'concepts/exactly-once',
        'concepts/snapshots',
        'concepts/schema-and-ddl',
        'concepts/multi-pdb',
      ],
    },
    {
      type: 'category',
      label: 'Database setup',
      link: {type: 'doc', id: 'database-setup/index'},
      items: ['database-setup/supplemental-logging', 'database-setup/redo-sizing'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Configuration',
          link: {type: 'doc', id: 'reference/configuration/index'},
          items: [{type: 'autogenerated', dirName: 'reference/configuration'}],
        },
        'reference/record-formats',
        'reference/metrics',
        'reference/ops-topic',
        'reference/error-classes',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/doctor',
        'operations/admin',
        'operations/signals',
        'operations/dashboards-and-alerts',
        {
          type: 'category',
          label: 'Runbooks',
          link: {type: 'doc', id: 'operations/runbooks/index'},
          items: [{type: 'autogenerated', dirName: 'operations/runbooks'}],
        },
        'operations/upgrade',
        'operations/security',
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      items: [
        'migration/tools',
        'migration/from-debezium',
        'migration/from-confluent',
        'migration/cutover-verification',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: ['development/building', 'development/local-testing', 'development/releasing'],
    },
    'comparison/index',
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: 'guides/index'},
      items: ['guides/oracle-cdc-to-kafka'],
    },
    'enterprise-support',
    {
      type: 'html',
      value: `<a class="sidebar-version__link" href="https://github.com/osodevops/kafka-connect-oracle-cdc/releases" target="_blank" rel="noopener noreferrer"><span class="sidebar-version__label">connector</span><span class="sidebar-version__badge">${connectorVersion}</span></a>`,
      className: 'sidebar-version',
    },
  ],
};

export default sidebars;
